#%RAML 1.0
title: sample-nov
/bankdetails:
  get:
    description: fetching the bank details
    responses:
      200:
        body:
          application/json:
            example:
              {
                "result":"fetching suceefylly"
              }
            
